SELECT
    t.TABLE_SCHEMA [schema],
    t.TABLE_NAME [table],
    c.COLUMN_NAME [column],
    c.DATA_TYPE [dataType]    
FROM	
	INFORMATION_SCHEMA.COLUMNS c 
	INNER JOIN 	INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE cc ON c.COLUMN_NAME = cc.COLUMN_NAME AND c.TABLE_NAME = cc.TABLE_NAME AND c.TABLE_SCHEMA = cc.TABLE_SCHEMA
	INNER JOIN  INFORMATION_SCHEMA.TABLE_CONSTRAINTS t ON t.TABLE_NAME = cc.TABLE_NAME AND t.CONSTRAINT_NAME = cc.CONSTRAINT_NAME
WHERE
	t.CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY 
	c.TABLE_SCHEMA, c.TABLE_NAME, c.COLUMN_NAME